
["args kwargs"]
text = "*args, **kwargs"
select = -1

["method"]
text = "\n    def method(self):\n        pass\n"
move = 21
select = 6

["print fstring"]
text = 'print(f"{expr=}")'
move = 4
select = 4

["property"]
text = '\n    @property\n    def property(self):\n        pass\n'
move = 21
select = 8

["class"]
text = '\nclass ClassName:\n    def __init__(self):\n        pass\n'
move = 39
select = 9

["class verbose"]
text = '\nclass ClassName(object):\n    def __init__(self, *args, **kwargs):\n        super().__init__(*args, **kwargs)\n'
move = 93
select = 9

["docstring"]
text = '"""Docstring"""'
move = 3
select = 9

["code snippet"]
text = "\n```\n```\n"
move = 5

["code snippet python"]
text = "\n```python\n\n```\n"
move = 5
