# The snippets file defines shortcuts for inserting text.
# There are no underlying defaults and so whatever is defined in this file
# are the only snippets recognized by Positron.

["args kwargs"]
text = "*args, **kwargs"
select = -1

["method"]
text = """

    def method(self):
        pass
"""
move = 21
select = 6

["print fstring"]
text = 'print(f"{expr=}")'
move = 4
select = 4

["property"]
text = """

    @property
    def property(self):
        pass
"""
move = 21
select = 8

["class"]
text = """

class ClassName:
    def __init__(self):
        pass
"""
move = 39
select = 9

["class verbose"]
text = """

class ClassName:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
"""
move = 85
select = 9

["docstring"]
text = '"""Docstring"""'
move = 3
select = 9

["code snippet"]
text = """

```
```
"""
move = 5

["code snippet python"]
text = """

```python

```
"""
move = 5
