
[window]
maximize = true
border = true
size = [1280, 800]
offset = [-1, -1]
fps = 10


[ui]
cols = 2
rows = 1
# Background colors of the status bar
status.normal = [0, 0, 0]
status.warn = [0.15, 0.15, 0]
status.error = [0.25, 0, 0]


[editor]
style = "one-dark"
bg_color = [0.025, 0.1, 0.125]
# Background relative brightness when defocused
defocus_brightness = 0.5
# Color of the max line length hint
line_width_color = [0.5, 0, 0, 0.5]
# Width of line gutter in characters
gutter_width = 4
# Color of line gutter numbers
gutter_text_color = [0.9, 1, 0.9]
# Color of line gutter background
gutter_bg_color = [0.05, 0.1, 0.05]
# Number of seconds between checking difference from disk
disk_diff_interval = 1.0
# Number of seconds to show popup on cursor
cursor_pause_timeout = 0.25
# Number of lines to offset when scrolling to cursor
cursor_scroll_offset = 10
# Never check for errors more than once per this many seconds
error_check_cooldown = 2
# Maximum file size to allow loading in editor in KB
max_file_size_kb = 500
# Automatically load the file on startup
auto_load = true


# Fonts - pass full path to font: "/path/to/font.ttf" or leave blank for builtins
[fonts.code]
size = 16
regular = ""
italic = ""
bold = ""
bolditalic = ""

[fonts.ui]
size = 20
regular = ""
italic = ""
bold = ""
bolditalic = ""


[linter]  # Settings for the linter (flake8).
# Error codes to ignore (using comma-separated values)
ignore = "E203,"
# Maximum line length (79-80 according to pep8, 88 according to black)
max_line_length = 88
# Maximum cyclomatic complexity (see: https://en.wikipedia.org/wiki/Cyclomatic_complexity)
max_complexity = 10
# Docstring convention to use
docstring_convention = "google"
# Paths to exclude from the global linter
exclude = [
    "__pycache__",
    "venv",
    "build",
]


[project]
# Default project to open
default = "~/.local/share/positron/"
# For new projects, open the following files
open = [
    "~/.local/share/positron/HELP.md",
    # Paths that begin with "./" are relative to the project folder
    # "./relative/path/from/project",
    # "absolute/path/from/disk",
]
# Ignore any file without one of the following extensions
file_types = [
    "py",
    "txt",
    "md",
    "toml",
    "json",
    "sh",
    "log",
    "",  # For files without extensions (like .gitignore)
]
# Ignore any file with the following names found anywhere in the path
ignore_names = [
    ".git",
    "venv",
    "build",
    "__pycache__",
    ".pytest_cache",
    ".hypothesis",
    ".egg-info/",
]
# Maximum seconds to try indexing directories
indexing_timeout = 10
# Maximum number of items to allow fuzzy search in tree
tree_fuzzy_threshold_count = 2000
# How fuzzy to make the tree search (higher = more results)
tree_search_fuzziness = 20
# How many seconds to cooldown before searching the project tree
tree_search_cooldown = 0.1
# Maximum text search results to show
max_search_results = 100
# How many seconds to cooldown before searching the entrie project for text
text_search_cooldown = 0.2
# Paths on disk for quick access in disk browser
bookmarks = [
    # Use ";" to name the bookmark
    # "~/path/to/folder/or/file;[color=#ffffff]Bookmark Name[/color]",
    "~/;Home folder",
    "~/.local/share/positron/;Positron config",
]


[path_prefixes]
# When displaying paths, replace using these prefixes (first one that matches)
home = "~"
config = "#"
project = "$"
custom = [
    # Display "/folder/path/file.py" as "PREFIX/file.py":
    # "/folder/path/;PREFIX",
]


[debug.hotkeys]
press = false
release = false
